// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZPHqfjRtp3BjOVJG9QNdfJde1NBceO0',
    appId: '1:845947477263:web:deb5ac82aa06947dc1327a',
    messagingSenderId: '845947477263',
    projectId: 'android-club-65a70',
    authDomain: 'android-club-65a70.firebaseapp.com',
    storageBucket: 'android-club-65a70.appspot.com',
    measurementId: 'G-45FZBQZJPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxv-m7Enu85kKsbrk5PZw8HGQ8GxHhcaA',
    appId: '1:845947477263:android:acd7d8a4b21b9235c1327a',
    messagingSenderId: '845947477263',
    projectId: 'android-club-65a70',
    storageBucket: 'android-club-65a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApRT5cjhRf0mKmH0jDUxJ4kuoUJLx_Sr8',
    appId: '1:845947477263:ios:b5038a41cc5453a4c1327a',
    messagingSenderId: '845947477263',
    projectId: 'android-club-65a70',
    storageBucket: 'android-club-65a70.appspot.com',
    androidClientId: '845947477263-5o8j54i1b09a8htgf4hdk3jjjkdu9a1m.apps.googleusercontent.com',
    iosClientId: '845947477263-f08knsp133a1gvesg8j1fpplj2520h5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApRT5cjhRf0mKmH0jDUxJ4kuoUJLx_Sr8',
    appId: '1:845947477263:ios:b5038a41cc5453a4c1327a',
    messagingSenderId: '845947477263',
    projectId: 'android-club-65a70',
    storageBucket: 'android-club-65a70.appspot.com',
    androidClientId: '845947477263-5o8j54i1b09a8htgf4hdk3jjjkdu9a1m.apps.googleusercontent.com',
    iosClientId: '845947477263-f08knsp133a1gvesg8j1fpplj2520h5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.androidClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlZPHqfjRtp3BjOVJG9QNdfJde1NBceO0',
    appId: '1:845947477263:web:cb1f07dfa0140fdfc1327a',
    messagingSenderId: '845947477263',
    projectId: 'android-club-65a70',
    authDomain: 'android-club-65a70.firebaseapp.com',
    storageBucket: 'android-club-65a70.appspot.com',
    measurementId: 'G-YM6ZCPT9MZ',
  );

}